// dark context
export const DARK = "DARK";
//invoice context
export const SET_IS_PENDING = "SET_IS_PENDING";
export const CHANGE_FILTERS = "CHANGE_FILTERS";
export const CURRENT_INVOICE_NUMBER = "CURRENT_INVOICE_NUMBER";
export const GET_ALL_INVOICES = "GET_ALL_INVOICES";
export const IS_DELETE_CONF = "IS_DELETE_CONF";
export const IS_EDIT_INVOICE = "IS_EDIT_INVOICE";
export const IS_NEW_INVOICE = "IS_NEW_INVOICE";
export const IS_PREVIEW_INVOICE = "IS_PREVIEW_INVOICE";
export const GET_INVOICE_ITEMS = "GET_INVOICE_ITEMS";
export const SET_CURRENT_INVOICE_ID = "SET_CURRENT_INVOICE_ID";
export const SET_DEFAULT_FILTERS = "SET_DEFAULT_FILTERS";