// dark context
export const DARK = "DARK";
//invoice context
export const IS_NEW_INVOICE = "IS_NEW_INVOICE";
export const CURRENT_INVOICE_NUMBER = "CURRENT_INVOICE_NUMBER";
export const IS_PREVIEW_INVOICE = "IS_PREVIEW_INVOICE";
export const IS_EDIT_INVOICE = "IS_EDIT_INVOICE";
export const CHANGE_FORM_STATE = "CHANGE_FORM_STATE";
export const RESET_FORM = "RESET_FORM";
export const CHANGE_FILTERS = "CHANGE_FILTERS";
export const CHANGE_SHOWN_INVOICES = "CHANGE_SHOWN_INVOCES";
export const MARK_AS_PAID = "MARK_AS_PAID";
export const IS_DELETE_CONF = "IS_DELETE_CONF";
export const CONFIRM_DELETE = "CONFIRM_DELETE";
export const ADD_NEW_FORMFIELD = "ADD_NEW_FORMFIELD";
export const DELETE_NEW_FORMFIELD = "DELETE_NEW_FORMFIELD";
export const ADD_TO_ALL_INVOICES = "ADD_TO_ALL_INVOICES"